In [ ]:
Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).



In [1]:
import numpy as np

In [55]:
np.arange(0, 10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.



In [46]:
def my_diag(max_number):
    my_np =  np.zeros( (max_number, max_number) )
    for i in range(max_number):
        my_np[max_number-1-i][max_number-1-i] = i
    return my_np

In [47]:
my_diag(10)

array([[9., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 7., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 6., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 4., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [62]:
a =  np.arange(0, 10)[::-1]

In [63]:
np.diag(a)

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [77]:
# сумма элементов 

np.sum(np.diag(a))

45

In [ ]:
Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [48]:
M1 = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]]) 
v1 = np.array([4, 12,-3])

In [78]:
calc = np.linalg.solve(M1, v1)
print('x='+str(round(calc[0],2))+' , y='+str(round(calc[1],2))+' , z='+str(round(calc[2],2)))

x=0.47 , y=3.84 , z=-5.56


In [ ]:

Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”

In [64]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [65]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [66]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [76]:
cos_r = 0

for i in users_stats:
    if cos_r<cosine( i, next_user_stats ):
        cos_r = cosine( i, next_user_stats )
        res = i
print(res)

[0 1 1 0 0 0]
